import { PromptCategory } from './types';

export const LOADING_MESSAGES: string[] = [
  "Analyzing your photo...",
  "Applying artistic styles...",
  "Rendering your new portrait...",
  "Adding professional touches...",
  "Finalizing the transformation...",
  "Almost ready...",
];

export const EXAMPLE_PROMPTS: PromptCategory[] = [
  {
    title: "Professional Headshots",
    prompts: [
      { prompt: "Using the uploaded photo, generate a crisp, professional corporate headshot. Dress the person in a dark, well-fitted business suit and place them against a soft-focus, modern office background with geometric patterns. Ensure the lighting is a clean, three-point setup that chisels the jawline and adds a catchlight to the eyes, making sure the face is the clear focus.", imageUrl: "https://images.pexels.com/photos/9954704/pexels-photo-9954704.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Transform the uploaded photo into a warm and approachable headshot for a creative director. Change the attire to a smart-casual blazer over a simple, high-quality t-shirt. Position the person in a bright, naturally lit studio with a seamless, light-gray backdrop. The lighting should feel soft and airy, creating a friendly and open expression where the face is clearly visible.", imageUrl: "https://images.pexels.com/photos/762080/pexels-photo-762080.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "From the uploaded image, produce a powerful, executive-style portrait for a CEO. Dress the person in high-end, bespoke business attire. The background should be a minimalist, dark, and textured wall, perhaps with a subtle, luxurious material like slate or dark wood. Use dramatic, high-contrast 'Rembrandt' lighting to create a serious, confident, and commanding mood, with the face sharply defined and clearly visible.", imageUrl: "https://images.pexels.com/photos/8353802/pexels-photo-8353802.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Using the base photo, generate a clean, modern headshot for a tech innovator. The person should be wearing a simple, dark-colored merino wool sweater. The background should be a clean, out-of-focus server room or a futuristic office space with subtle, cool-toned blue and white lighting accents. The overall feel should be sharp, intelligent, and forward-thinking, with a clear and focused view of the person's face.", imageUrl: "https://images.pexels.com/photos/4974914/pexels-photo-4974914.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Transform the person in the photo into a friendly and professional healthcare provider. Change their clothes to professional, well-fitting scrubs in a calming teal color, or a crisp lab coat over a collared shirt. The background should be a clean, bright, and slightly blurred medical office or modern hospital hallway, conveying competence and empathy, with a clear, well-lit, and friendly facial expression.", imageUrl: "https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Modify the uploaded image to show the person as a distinguished author for a book cover. Use soft, moody, and directional lighting. The background should be a cozy, out-of-focus library or study, with warm tones from a nearby lamp. The expression should be thoughtful, engaging, and slightly mysterious, with the face in sharp focus.", imageUrl: "https://images.pexels.com/photos/6947271/pexels-photo-6947271.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Using the photo, generate a dynamic portrait of a skilled chef. Place them in a professional chef's uniform, clean and white. The background should be a blurred, high-end kitchen with stainless steel surfaces and warm lighting. The expression should be passionate and confident, ensuring the face is clearly visible.", imageUrl: "https://images.pexels.com/photos/3217157/pexels-photo-3217157.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Create a headshot of the person in the photo as a software engineer. They should be wearing a stylish, branded company hoodie or a casual button-down shirt. The background should be an artistic mural wall from a modern tech campus, artistically blurred. Use natural light coming from a large window to the side, highlighting their facial features clearly.", imageUrl: "https://images.pexels.com/photos/5439427/pexels-photo-5439427.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "From the uploaded image, produce a portrait of a financial advisor. Attire should be a sharp, conservative suit. The background should be a classic boardroom with a view of a city skyline, heavily blurred to keep the focus on the subject. Lighting should be professional and balanced, conveying trust and stability, with a clear view of the person's face.", imageUrl: "https://images.pexels.com/photos/7648995/pexels-photo-7648995.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Generate a headshot of the person from the photo as a musician or artist. Their clothing should reflect their personal style, be it bohemian, edgy, or classic. The background should be a textured, solid color, like a deep charcoal or a rich burgundy. Use a single, dramatic light source to create an artistic and intense mood, making the face the clear subject.", imageUrl: "https://images.pexels.com/photos/1684369/pexels-photo-1684369.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Transform the person in the photo into an architect. They should be wearing a turtleneck sweater and stylish glasses. Position them in front of a blurred background featuring one of their architectural models or a blueprint design. The lighting should be sharp and angular, highlighting structure, form, and their clearly visible facial features.", imageUrl: "https://images.pexels.com/photos/3807755/pexels-photo-3807755.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Modify the photo to be a headshot for a fitness trainer. Change their attire to high-quality athletic wear. The background should be a modern, clean gym with artistic lens flare, out of focus. Their expression should be energetic, motivating, and confident, with their face clearly visible.", imageUrl: "https://images.pexels.com/photos/4761793/pexels-photo-4761793.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Using the photo, generate a headshot for a lawyer. They should be in a very sharp, traditional suit. The background should be a courthouse steps or a law library, tastefully and heavily blurred. The lighting should be strong and direct, conveying authority and seriousness, with the face clearly defined.", imageUrl: "https://images.pexels.com/photos/6077326/pexels-photo-6077326.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Create a portrait of the person from the photo as a real estate agent. Dress them in a polished, professional, yet friendly outfit. The background should be the blurred interior of a luxurious modern home. The lighting should be bright and welcoming, with a warm, trustworthy smile and a clear view of their face.", imageUrl: "https://images.pexels.com/photos/8481920/pexels-photo-8481920.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Produce a headshot of the subject as a university professor. They should be wearing a tweed jacket or academic robes. The background should be a classic, wood-paneled office or lecture hall, completely out of focus. The expression should look wise, approachable, and intellectual, with the face clearly visible and well-lit.", imageUrl: "https://images.pexels.com/photos/5212345/pexels-photo-5212345.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "From the uploaded photo, generate a portrait of a journalist. Dress them in practical but professional attire, like a trench coat. The background should be a blurred, bustling city street or a newsroom. The lighting should be naturalistic and slightly gritty, and their expression should be alert and focused, and their face clearly visible.", imageUrl: "https://images.pexels.com/photos/8090137/pexels-photo-8090137.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Transform the person in the photo into a graphic designer. Attire should be trendy and creative. The background should be a simple, colorful wall or a studio space with design tools blurred behind them. Lighting should be vibrant and clean, reflecting a creative personality with a clearly visible face.", imageUrl: "https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Using the photo, produce a portrait of a veterinarian. Change their clothes to professional scrubs. The background should be a bright and clean examination room, very out of focus. Their expression should be compassionate, gentle, and caring, with a clear view of their face.", imageUrl: "https://images.pexels.com/photos/6235116/pexels-photo-6235116.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Generate a headshot of the person in the photo as a pilot. Dress them in a crisp pilot uniform. The background should be a blurred view of an airport tarmac or cockpit. The lighting should be clear and bright, like a sunny day, with their expression confident and assured, and their face clearly visible.", imageUrl: "https://images.pexels.com/photos/3061224/pexels-photo-3061224.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Create a portrait of the person from the photo as a retail manager. They should be in business-casual attire. The background should be the interior of a modern, stylish store, heavily blurred into abstract shapes and colors. Their expression should be helpful, friendly, and professional, with a clearly visible face.", imageUrl: "https://images.pexels.com/photos/3760067/pexels-photo-3760067.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" }
    ]
  },
  {
    title: "Hairstyles",
    prompts: [
      { prompt: "Using the uploaded photo, change the hairstyle to a sharp, chin-length bob cut. The hair should be straight and sleek with a center part. The person's face must remain clearly visible and recognizable.", imageUrl: "https://images.pexels.com/photos/3065209/pexels-photo-3065209.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Modify the person's hair in the photo to be a classic pompadour style, with the hair swept upwards and back from the face. The sides should be shorter and neatly faded. Ensure the original facial features are preserved.", imageUrl: "https://images.pexels.com/photos/2893943/pexels-photo-2893943.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Transform the hair into long, cascading curls that fall well past the shoulders. Add significant volume and texture to the curls, making them look natural, soft, and bouncy. The person's face must be the central focus and clearly recognizable.", imageUrl: "https://images.pexels.com/photos/1115680/pexels-photo-1115680.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Give the person in the photo a modern buzz cut. The hair should be uniformly short all over, creating a clean and sharp look. Make sure the original face shape and features are unchanged.", imageUrl: "https://images.pexels.com/photos/3998418/pexels-photo-3998418.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Using the uploaded image, change the hairstyle to a chic pixie cut. The hair should be short on the sides and back, with slightly more length and texture on top. The person's face and expression must be the main focus.", imageUrl: "https://images.pexels.com/photos/4006576/pexels-photo-4006576.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Modify the hairstyle to be a high, sleek ponytail. The hair should be pulled back tightly from the face, with the ponytail positioned at the crown of the head. The facial features must remain clear and unchanged.", imageUrl: "https://images.pexels.com/photos/3738346/pexels-photo-3738346.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Give the person in the photo a 'curtain bangs' hairstyle. The fringe should be parted in the middle and swept to each side, framing the face. The rest of the hair should be shoulder-length and wavy. The person's face must be clearly visible.", imageUrl: "https://images.pexels.com/photos/6954215/pexels-photo-6954215.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Transform the hair into an intricate braided style, like cornrows or a crown braid. The braids should be neat and detailed. The face must remain fully visible and be the focus of the portrait.", imageUrl: "https://images.pexels.com/photos/5638268/pexels-photo-5638268.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Using the photo, change the hair color to a vibrant, fiery red. Keep the current hairstyle but ensure the new color is rich and multi-dimensional, with realistic highlights and lowlights. The person's face must be unaffected.", imageUrl: "https://images.pexels.com/photos/1536440/pexels-photo-1536440.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Modify the hair to be platinum blonde with dark roots, creating a trendy, high-contrast look. The style should be a textured, medium-length shag. The original facial features must be preserved perfectly.", imageUrl: "https://images.pexels.com/photos/8141163/pexels-photo-8141163.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Give the person in the photo soft, beachy waves. The hair should look naturally sun-kissed and slightly tousled, as if they've spent a day by the ocean. The face must be clearly visible and relaxed.", imageUrl: "https://images.pexels.com/photos/2433346/pexels-photo-2433346.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Change the hairstyle to a classic crew cut, very short on the sides and back, with a slightly longer length on top that can be styled. This should look neat and professional, without altering the person's face.", imageUrl: "https://images.pexels.com/photos/2529174/pexels-photo-2529174.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Transform the person's hair into a voluminous afro. The texture should be tightly coiled and the shape well-defined. The face must remain the clear focal point of the image.", imageUrl: "https://images.pexels.com/photos/4057751/pexels-photo-4057751.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Using the uploaded photo, give the person an undercut hairstyle, where the sides and back are shaved short, while the hair on top is left significantly longer and styled. The facial features must not be changed.", imageUrl: "https://images.pexels.com/photos/1805606/pexels-photo-1805606.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Modify the hair to have pastel pink and blue highlights, creating a soft, 'cotton candy' effect. The base hairstyle should be long and straight. The person's face must be clearly visible.", imageUrl: "https://images.pexels.com/photos/7175440/pexels-photo-7175440.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Give the person in the photo a classic, side-parted hairstyle often seen in the 1950s. The hair should be neatly combed, with a bit of volume and a healthy shine. The original face must be perfectly preserved.", imageUrl: "https://images.pexels.com/photos/2583852/pexels-photo-2583852.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" }
    ]
  },
  {
    title: "Closeup Portraits",
    prompts: [
      { prompt: "A tight close-up portrait of the person from the photo during the golden hour. Their face is bathed in warm, soft, glowing sunlight, with lens flare creating a dreamy effect. The background is a blurred field of wildflowers. Their expression should be serene, and their face must be clearly visible.", imageUrl: "https://images.pexels.com/photos/1579253/pexels-photo-1579253.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Generate a close-up portrait based on the uploaded image, capturing the person's profile against a golden hour sunset over the ocean. The warm light should highlight the contours of their face and create a silhouette effect on their hair. Their face, in profile, must be sharp and clearly visible.", imageUrl: "https://images.pexels.com/photos/937453/pexels-photo-937453.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Close-up headshot of the person in the photo, looking directly at the camera. They are lit by the magical, warm light of the golden hour. The background is a bustling city street, blurred into a beautiful bokeh. Their eyes should sparkle, and their face must be perfectly in focus and clearly visible.", imageUrl: "https://images.pexels.com/photos/1310522/pexels-photo-1310522.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "An intimate close-up portrait of the person from the photo, smiling gently. The scene is set on a balcony at sunset, with the golden light filtering through their hair. The focus is entirely on their happy expression, with their face clearly visible.", imageUrl: "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Using the uploaded image, create a golden hour close-up portrait. The person is laughing, with their head tilted back slightly. The warm sunlight catches the details of their expression, and their face is the clear, sharp focus of the image.", imageUrl: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Create a close-up portrait of the person from the photo on a rainy night in a city like Tokyo. Their face is illuminated by the vibrant, colorful glow of neon signs, with reflections of the lights in their eyes and on their wet skin. Their face must be clearly visible and the focus of the shot.", imageUrl: "https://images.pexels.com/photos/3389537/pexels-photo-3389537.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" }
    ]
  },
  {
    title: "Sci-Fi & Fantasy Portraits",
    prompts: [
      { prompt: "Using the uploaded photo, reimagine the person as a gritty cyberpunk mercenary. Add subtle cybernetic facial implants, a glowing data-jack port on their temple, and a faint, glowing geometric tattoo on their neck. The background should be a rain-slicked, neon-lit alley in a futuristic city, ensuring their original facial features remain clearly recognizable under the augmentations.", imageUrl: "https://images.pexels.com/photos/9894348/pexels-photo-9894348.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Convert the person from the photo into a high-fantasy wood elf. Give them elegant, pointed elven ears, intricate silver filigree woven into their long, flowing hair, and subtle, nature-inspired facial markings, ensuring their face is serene and clearly visible.", imageUrl: "https://images.pexels.com/photos/10777375/pexels-photo-10777375.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Transform the person in the photo into a decorated Starship Fleet captain. Change their clothes into a sleek, dark blue and silver futuristic uniform with a subtle, glowing insignia on the collar. The background should be the command bridge of a starship, and their confident expression and face must be clearly visible.", imageUrl: "https://images.pexels.com/photos/13045688/pexels-photo-13045688.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Create a portrait of the subject as a powerful sorcerer from a dark fantasy world. Add a mystical, ethereal glow to their eyes and have magical energy crackling around their fingertips. Their attire should be dark, ornate robes, ensuring their powerful facial expression is the central focus.", imageUrl: "https://images.pexels.com/photos/11303866/pexels-photo-11303866.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" }
    ]
  },
  {
    title: "Traveling & Adventure",
    prompts: [
      { prompt: "Using the uploaded photo, place the person on a scenic clifftop in Santorini, Greece, at sunset. Their clothing should be light and summery. The background shows the iconic white and blue buildings. The person's face should be clearly visible and smiling.", imageUrl: "https://images.pexels.com/photos/3454270/pexels-photo-3454270.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Modify the uploaded photo to show the person exploring the ancient ruins of Machu Picchu, Peru. Dress them in practical hiking gear. The background should be misty mountains. The person's face should be clearly visible, showing a sense of wonder.", imageUrl: "https://images.pexels.com/photos/1612845/pexels-photo-1612845.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Reimagine the person from the photo backpacking through a bustling, vibrant street market in Marrakesh, Morocco. The background should be filled with colorful spices and lanterns, with the person's engaged face clearly visible.", imageUrl: "https://images.pexels.com/photos/1799904/pexels-photo-1799904.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Create an action shot of the person from the photo kayaking through a dramatic fjord in Norway. The water is calm and reflective. They are wearing appropriate kayaking gear, and their exhilarated facial expression is clearly visible.", imageUrl: "https://images.pexels.com/photos/2440134/pexels-photo-2440134.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" }
    ]
  },
  {
    title: "Dangerous Adventures",
    prompts: [
       { prompt: "Using the uploaded photo, place the person navigating the treacherous 'Bottleneck' on K2. They are in full high-altitude climbing gear under a massive, looming serac. The weather is harsh, conveying extreme danger and determination. Their face, though partially protected by goggles, must be clearly visible and show grit.", imageUrl: "https://images.pexels.com/photos/7137536/pexels-photo-7137536.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
       { prompt: "Transform the uploaded photo to show the person standing triumphantly on the summit of Mount Everest. They are wearing a brightly colored down suit and have pulled their oxygen mask aside for the triumphant summit photo, with their face clearly visible and filled with emotion. The background is a breathtaking panorama of the Himalayas.", imageUrl: "https://images.pexels.com/photos/7441761/pexels-photo-7441761.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" }
    ]
  },
  {
    title: "Magazine Covers",
    prompts: [
      { prompt: "Transform the uploaded photo into a cover for 'VOGUE' magazine. Style the person in avant-garde high fashion with artistic, dramatic lighting that ensures their face is the main focus. Add the 'VOGUE' masthead at the top.", imageUrl: "https://images.pexels.com/photos/3222295/pexels-photo-3222295.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Using the photo, create a 'Forbes' magazine cover, featuring the person as a successful entrepreneur in sharp business attire. The pose should be confident and powerful, with their face clearly and professionally lit. Add the 'Forbes' logo and a headline.", imageUrl: "https://images.pexels.com/photos/3760069/pexels-photo-3760069.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" }
    ]
  },
  {
    title: "Celebrity Encounters",
    prompts: [
      { prompt: "Edit the uploaded photo to show the person sharing a candid, laughing moment with Keanu Reeves on a park bench. The style should be natural, with both of their faces clearly visible and expressive.", imageUrl: "https://images.pexels.com/photos/15724458/pexels-photo-15724458/free-photo-of-keanu-reeves-sitting-on-a-bench.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Using the photo, place the person on a red carpet premiere, standing next to Zendaya. Both are in glamorous, high-fashion attire, with paparazzi flashbulbs in the background. The faces of both individuals should be clearly visible.", imageUrl: "https://images.pexels.com/photos/17693992/pexels-photo-17693992/free-photo-of-zendaya-at-the-premiere-of-the-movie-challengers-in-london.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" }
    ]
  },
  {
    title: "Posters & Politics",
    prompts: [
      { prompt: "Using the person from the photo, create a powerful political campaign poster. They should look determinedly towards the future. Use a patriotic color scheme, and their face must be clearly visible and inspiring. Add a slogan like 'Hope & Progress'.", imageUrl: "https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Transform the uploaded image into a photorealistic political campaign poster. The person should have a determined, hopeful expression. The lighting should be dramatic and inspiring. Add subtle, modern graphic elements and a slogan like 'A New Vision'.", imageUrl: "https://images.pexels.com/photos/1040881/pexels-photo-1040881.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" }
    ]
  },
  {
    title: "Fun Selfies",
    prompts: [
      { prompt: "Using the uploaded photo, generate a fun selfie of the person with a curious lemur on their shoulder. Their smiling face should be the focus of the selfie and clearly visible.", imageUrl: "https://images.pexels.com/photos/5472251/pexels-photo-5472251.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" },
      { prompt: "Create a selfie of the person from the photo smiling happily next to a friendly, fluffy alpaca on a sunny farm; their face should be clearly visible.", imageUrl: "https://images.pexels.com/photos/5676342/pexels-photo-5676342.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=1" }
    ]
  }
];