import React from 'react';
import { DownloadIcon } from './Icons';

interface ImageDisplayProps {
  imageUrls: string[];
}

const ImageDisplay: React.FC<ImageDisplayProps> = ({ imageUrls }) => {
  return (
    <div className="w-full animate-fade-in">
      <div className={`grid gap-4 ${imageUrls.length > 1 ? 'grid-cols-2' : 'grid-cols-1'}`}>
        {imageUrls.map((url, index) => (
          <div key={index} className="group relative">
            <img
              src={url}
              alt={`Generated by AI ${index + 1}`}
              className="w-full h-full object-cover rounded-lg shadow-lg border-2 border-gray-700"
            />
            <a
              href={url}
              download={`generated-image-${index + 1}.png`}
              className="absolute bottom-2 right-2 inline-flex items-center justify-center p-2 bg-green-600 text-white font-bold rounded-full shadow-lg opacity-0 group-hover:opacity-100 transition-opacity duration-300 hover:bg-green-700 transform hover:-translate-y-0.5"
              aria-label="Download Image"
            >
              <DownloadIcon className="w-5 h-5" />
            </a>
          </div>
        ))}
      </div>
    </div>
  );
};

export default ImageDisplay;